function showSolution(error){


var solution=document.getElementById("solution");
solution.style.display="block";
if(error=="slow"){
solution.innerHTML="<b>1. Close Unnecessary Programs. </b><br> Step 1 - Press Ctrl + Shift + Esc on the keyboard.<br> Step 2 - Task Manager will open. <br> Step 3 - Click on the Processes tab. <br> Step 4 - Look for programs that are using high CPU or Memory.<br>Step 5 - Select the unnecessary program.<br>Step 6 - Click End Task to close it.<br><br><b> 2. Run Disk Cleanup.</b><br> Step 1 - Open This PC on your Computer.<br>Step 2 - Right Click on Local Disk (C:).<br> Step 3 - Click on Properties. <br>Step 4 - Click the Disk Cleanup Button. <br> Step 5 - Select the Files you want to Delete(Temporary files, Recycle bin, etc.).<br> Step 6 - Click OK ,then delete files. <br><br> <b>3. Scan For Virus.</b><br> Step 1 - Open your Antivirus Software(for example Windows Security).<br> Step 2 - Go to Virus and Threat Protection.<br> Step 3 - Click on Scan options.<br> Step 4 - Select Full Scan.<br> Step 5 - Click Scan Now.<br> Step 6 - Wait for the scan to finish and remove any detected viruses.";
}

else if(error=="internet"){
solution.innerHTML="<b>1. Check WiFi Connection. </b><br> Step 1 - Look at the Wi-Fi on the taskbar (botton right of the scren).<br> Step 2 - Click on the Wi-Fi icon.<br> Step 3 - Check if Wi-Fi is turned ON.<br> Step 4 - Select your Wi-Fi network name from the list.<br> Step 5 - Click Connect.<br> Step 6 - Enter the Wi-Fi password if required.<br><br> <b>2. Restart Router.</b><br> Step 1 - Find the power button on the router.<br> Step 2 - Press the button to turn OFF the router.<br> Step 3 - Wait for 10-15 seconds.<br> Step 4 - Turn the router ON again.<br> Step 5 - Wait until the internet lights become stable.<br> Step 6 - Reconnect your computer to the Wi-Fi network. <br><br><b> 3. Reconnect Network.</b><br> Step 1 - Click the Wi-Fi icon on the taskbar (bottom right corner).<br> Step 2 - Select your connected Wi-Fi network. <br> Step 3 - Click Disconnect.<br> Step 4 -Wait for a few seconds.<br> Step 5 - Select the same Wi-Fi network again.<br> Step 6 - Click Connect and enter the password if required. ";
}

else if(error=="usb"){
solution.innerHTML="<b>1. Change USB Port.</b><br> Step 1 - Remove the USB device from the current port<br> Step 2 - Look for another USB port on the computer or laptop.<br> Step 3 - Insert the USB device into the new USB port.<br> Step 4 - Wait a few seconds for the computer to detect the device.<br> Step 5 - Check This PC to see if the USB device appears.<br><br> <b>2. Restart Computer.</b><br> Step 1 - Click the Start button on the screen.<br> Step 2 - Click the Power icon.<br> Step 3 - Select Restart.<br> Step 4 - Wait for the computer to restart completely.<br> Step 5 - After restarting, insert the USB device again and check if it is detected.<br><br><b>3. Reinstall USB Drivers.</b><br> Step 1 - Open Device Manager.<br> Step 2 - Find Universal Serial Bus Controllers.<br> Step 3 - Right-click on the USB driver.<br> Step 4 - Click Uninstall Device.<br> Step 5 - Restart the computer.<br> Step 6 - Windows will automatically reinstall the USB drivers.";
}

else if(error=="printer"){
solution.innerHTML="<b>1. Check Printer Connection.</b><br> Step 1 - Check if the printer is turned ON.<br> Step 2 - Check the USB cable or Wi-Fi connection between the printer and computer.<br> Step 3 - Make sure the cable is properly connected to both devices.<br> Step 4 - If using Wi-Fi, ensure the printer is connected to the same network as the computer.<br> Step 5 - Try printing a test page to check if the printer works.<br><br><b>2. Restart Printer.</b><br> Step 1 - Press the power button to turn OFF the printer.<br> Step 2 - Wait for about 10–15 seconds.<br> Step 3 - Press the power button again to turn ON the printer.<br> Step 4 - Wait until the printer starts completely.<br> Step 5- Try printing the document again.<br><br><b>3. Reinstall Printer Driver.</b><br> Step 1 - Open Control Panel on the computer.<br> Step 2 - Click on Devices and Printers.<br> Step 3 - Right-click on the printer and select Remove Device.<br> Step 4 - Restart the computer.<br> Step 5 - Download the latest printer driver from the printer manufacturer’s website.<br> Step 6 - Install the driver and add the printer again.";
}

else if(error=="keyboard"){
solution.innerHTML="<b>1. Check the Keyboard Connection.</b><br> Step 1 - Check if the keyboard cable is properly connected to the computer.<br> Step 2 - Remove the keyboard USB cable from the port.<br> Step 3 - Insert the keyboard again into the USB port properly.<br> Step 4 - Try connecting the keyboard to another USB port.<br> Step 5 - Check if the keyboard starts working.<br><br><b>2. Try another USB Port.</b><br> Step 1 - Remove the keyboard USB cable from the current port.<br> Step 2 - Find another USB port on the computer or laptop.<br> Step 3 - Insert the keyboard cable into the new USB port.<br> Step 4 - Wait a few seconds for the computer to detect the keyboard.<br> Step 5 - Check if the keyboard starts working.<br><br> <b>3. Restart the Computer.</b><br> Step 1 -Click the Start button on the screen.<br> Step 2 - Click the Power icon.<br> Step 3 - Select Restart.Wait for the computer to restart completely.<br> Step 4 - After restarting, check if the keyboard is working.<br><br> <b>4. Reinstall the Keyboard Driver.</b><br> Step 1 - Open Device Manager on the computer.<br> Step 2 - Find and expand the Keyboards section.<br> Step 3 - Right-click on the keyboard driver.<br> Step 4 - Click Uninstall Device.<br> Step 5 - Restart the computer.<br> Step 6 - Windows will automatically reinstall the keyboard driver.";
}

else if(error=="mouse"){
solution.innerHTML="<b>1. Reconnect the Mouse.</b><br> Step 1 - Remove the mouse USB cable from the computer.<br> Step 2 - Wait for a few seconds.<br> Step 3 - Insert the mouse USB cable bac into the USB port.<br> Step 4 - Wait for the computer to detect the mouse.<br> Step 5 - Move the mouse to check if it starts working.<br><br><b>2. Try another USB Port.</b> <br> Step 1 - Remove the mouse USB cable from the current port.<br> Step 2 - Find another USB port on the computer or laptop.<br> Step 3 - Insert the mouse cable into the new USB port.<br> Step 4 - Wait a few seconds for the computer to detect the mouse.<br> Step 5 - Move the mouse and check if it starts working.<br><br><b>3. Check Bettry (for wireless mouse).</b><br> Step 1 - Turn the wireless mouse OFF.<br> Step 2 - Open the battery cover on the back of the mouse.<br> Step 3 - Remove the old batteries.<br> Step 4 - Insert new batteries properly.<br> Step 5 - Close the battery cover and turn the mouse ON.<br> Step 6 - Move the mouse and check if it starts working.<br><br><b>4. Restart the Computer.</b><br> Step 1 - Click the Start button on the screen.<br> Step 2 - Click the Power icon.<br> Step 3 - Select Restart.<br> Step 4 - Wait for the computer to restart completely.<br> Step 5 - After restarting, check if the mouse is working.";
}

else if(error=="wi-fi"){
solution.innerHTML="<b>1. Check the Wi-Fi Password.</b><br> Step 1 - Click the Wi-fi icon on the taskbar at the bottom right of the screen.<br> Step 2 - Make sure Wi-fi is turned ON.<br> Step 3 - Look for your Wi-fi network name inthe list.<br> Step 4 - Click on your Wi-fi network.<br> Step 5 - Click Connect.<br> Step 6 - Enter the wi-fi password if required and check if the internet connects. <br><br><b>2. Run Network Troubleshooter.</b> <br> Step 1 - Click the start button.<br> Step 2 - Open Settings.<br> Step 3 - Go to Network & Internet.<br> Step 4 - Click on Status.<br> Step 5 - Select Network Troubleshooter.<br> Step 6 - Folow the instruction to detect and fix the network problem.<br><br><b>3. Restart the Router.</b><br> Step 1 - Locate the router power button or power cable.<br> Step 2 - Turn OFF the router by pressing the power button or unpllugging the cable.<br> Step 3 - Wait for about 10-15 seconds.<br> Step 4 - Turn the router ON again or plug the power cable back in.<br> Step 5 - Wait until the router lights become stable.<br><br> <b>4. Update the WI-FI Driver.</b><br> Step 1 - Right-click on the Start button.<br> Step 2 - Click Device Manager.<br> Step 3 - Find and expand Network Adapters.<br> Step 4 - Right-click on the Wi-fi adapter.<br> Step 5 - Click update Driver.<br> Step 6 - Select Search automatically for drivers and follow the instruction.";
}

else if(error=="screen"){
solution.innerHTML="<b>1. Restart the Computer.</b><br> Step 1 - Press and hold the Power button on the computer.<br> Step 2 - Wait until FF.<br> Step 3 - Wait for a few seconds.<br> Step 4 - Press the Power button again to turn the computer ON.<br> Step 5 - Wait for the system to start normally.<br><br> <b>2. Update Windows and Drivers.</b> <br> Step 1 - Click the Start button.<br> Step 2 - Open Settings.<br> Step 3 - Go to Update & Security.<br> Step 4 Click Windows Updates.<br> Step 5 -  Click check for Updates.<br> Step 6 - Download and install the available updates, then restart the computer.<br><br> <b>3. Uninstall Recent Software.</b><br> Step 1 - Click the start button.<br> Step 2 - Open Control Panel<br> Step 3 - Click Programs and Features.<br> Step 4 - Find the recently installed software in the list.<br> Step 5 - Select the software in the list.<br> Step 6 - Follow the instruction and restart the computer.";
}

else if(error=="start"){
solution.innerHTML="<b>1. Check the Power Cable.</b><br> Step 1 - Check if the power cable is properly connected to the compute.<br> Step 2 - Check if the power sockect is working.<br> Step 3 - Try using another power cable or socket if needed.<br> Step 4 - Press the power button to see if the computer starts.<br><br><b>2. Check the Power Supply.</b> <br> Step 1 - Make sure the power supply unit (PSU) is connected to the computer.<br> Step 2 - Check if the power supply cable is properly plugged into the socket.<br> Step 3 - Turn ON the power switch on the power supply.<br> Step 4 - Look for any power indicator lights on the computer.<br> Step 5 - Press the power button to see if the computer starts.<br><br><b>3. Remove External Devices.</b><br> Step 1 - Turn OFF the computer.<br> Step 2 - Remove all external devices such as USB drives, printers, external hard disks, and other accessories.<br> Step 3 - Leave only the keyboard, mouse, and monitor connected.<br> Step 4 - Press the power button to start the computer again.<br> Step 5 - Check if the computer starts normally.<br><br><b>4. Restart the Computer.</b><br> Step 1 - Press and hold the Power button on the computer.<br> Step 2 - Wait until the computer turns OFF completely.<br> Step 3 - Wait for about 5 - 10 seconds.<br> Step 4 - Press the Power button again to turn the computer ON.<br> Step 5 - Check if the computer starts normally.";
}

else if(error=="sound"){
solution.innerHTML="<b>1. Check the Volume is Muted.</b><br> Step 1 - Look at the speaker icon on the taskbar at the bottom right of the screen.<br> Step 2 - Click on the speaker icon.<br> Step 3 - Check if the mute option is ON.<br> Step 4 - If muted, click the icon to unmute the sound.<br> Step 5 - Move the volume slider up to increase the sound.<br><br> <b>2. Check Speaker Connection.</b> <br> Step 1 - Check if the speaker cable is properly connected to the computer.<br> Step 2 - Make sure the cable is plugged into the audio jack (green port).<br> Step 3 - Check if the speakers are turned ON.<br> Step 4 - Ensure the speaker power cable is connected to the power source.<br> Step 5 - Play some audio to check if the sound works.<br><br><b>3. Restart the Computer.</b><br> Step 1 - Click the Start button.<br> Step 2 - Click the Power icon.<br> Step 3 - Select Restart.<br> Step 4 - Wait for the computer to restart completely.<br> Step 5 - After restarting, play audio and check if the sound is working.<br><br> <b>4. Update the Sound Driver.</b><br> Step 1 - Right-click on the Start button.<br> Step 2 - Click Device Manager.<br> Step 3 - Find and expand Sound, Video and Game Controllers.<br> Step 4 - Right-click on the sound driver.<br> Step 5 - Click Update Driver.Select Search automatically for drivers and follow the instructions.";
}

else if(error=="application"){
solution.innerHTML="<b>1. Restart the Computer.</b><br> Step 1 - Click the Start button.<br> Step 2 - Click the Power icon.Select Restart.<br> Step 3 - Wait for the computer to restart completely.<br> Step 4 - After restarting, try to open the application again. <br><br><b>2. Reinstall the Application.</b> <br> Step 1 - Click the Start button.Open Control Panel.<br> Step 2 - Click Programs and Features.<br> Step 3 - Find the application in the list.<br> Step 4 - Select it and click Uninstall.<br> Step 5 - Download and install the application again.<br><br><b>3. Check System Compatibility.</b><br> Step 1 - Right-click on the application icon.<br> Step 2 - Click Properties.<br> Step 3 - Go to the Compatibility tab.<br> Step 4 - Check the option Run this program in compatibility mode.<br> Step 5 - Select a Windows version from the list.<br> Step 6 - Click Apply and then OK, then try to open the application again. <br><br><b>4. Update the Software.</b><br> Step 1 -  Open the application on the computer.<br> Step 2 - Go to the Settings or Help menu.<br> Step 3 - Click on Check for Updates.<br> Step 4 - If an update is available, click Download and Install.<br> Step 5- Wait for the update to complete.<br> Step 6 - Restart the application and check if it opens properly.<br>";
}

else if(error=="virus"){
solution.innerHTML="<b>1. Run a Full anti-virus Scan.</b><br> Step 1 - Open your Antivirus software on the computer.<br> Step 2 - Go to Virus & Threat Protection or Scan options.<br> Step 3 - Select Full Scan.Click Scan Now.<br> Step 4 - Wait until the scan checks all files and programs.<br> Step 5 - Remove or quarantine any detected viruses or malware.<br><br><b>2. Remove Suspicious Files.</b> <br> STep 1 - Open File Explorer on the computer.<br> STep 2 - Look for unknown or suspicious files and folders.Right-click on the suspicious file.<br> Step 3 - Click Delete.<br> Step 4 - Open the Recycle Bin.<br> Step 5 - Click Empty Recycle Bin to remove the file permanently <br> <br> <b>3. Restart the Computer.</b><br> Step 1 - Click the Start button.<br> Step 2 - Click the Power icon.<br> Step 3 - Select Restart.<br> Step 4 - Wait for the computer to restart completely.<br> Step 5 - After restarting, check if the system works normally.<br><br><b>4. Update the anti-virus Software.</b><br> Step 1 - Open the Antivirus software on the computer.<br> Step 2 - Go to the Settings or Update section.<br> Step 3 - Click Check for Updates.<br> Step 4 - Download and install the latest virus definitions.<br> Step 5 - Wait for the update to complete.<br> Step 6 - Run a scan again to check for viruses.";
}
else if(error=="harddisk"){
solution.innerHTML="<b>1. Delete Unnecessary Files.</b><br> Step 1 - Open File Explorer.Go to This PC.<br> Step 2 - Open Local Disk (C:) or the full drive.<br> Step 3 - Find unnecessary files or folders.<br> Step 4- Right-click on the file and click Delete.<br> Step 5 - Open Recycle Bin and click Empty Recycle Bin.<br><br><b>2. Empty the Recyclebin.</b> <br> Step 1 -  Locate the Recycle Bin icon on the desktop.<br> Step 2 - Right-click on the Recycle Bin.<br> Step 3 - Click Empty Recycle Bin.Click Yes to confirm.<br> step 4 - Wait for all files to bepermanently deleted.<br><br><b>3. Run Disk Cleanup.</b><br> Step 1 - Open This PC.<br> Step 2 - Right-click on Local Disk (C:).<br> Step 3 - Click Properties.<br> Step 4 - Click Disk Cleanup.<br> Step 5 - Select the files you want to delete.<br> Step 6- Click OK and then Delete Files.<br><br><b>4. Move FIle External Storage.</b><br> Step 1 - Connect an external storage device (USB drive or external hard disk) to the computer.<br> Step 2 - Open File Explorer.<br> Step 3 - Go to the files or folders you want to move.<br> Step4 - Right-click on the file and click Copy.<br> Step 5 - Open the external storage device.<br> Step 6 - Right-click and click Paste to move the files.";
}

else if(error=="freeze"){
solution.innerHTML="<b>1. Close Unnecessary Programs.</b><br> Step 1 - Press Ctrl + Shift + Esc to open Task Manager.<br> Step 2 - Go to the Processes tab.Look for programs using high CPU or Memory.<br> Step 3 - Select the unnecessary program.<br> Step 4 - Click End Task to close it.<br><br><b>2. Check RAM Usage.</b> <br> Step 1 - Press Ctrl + Shift + Esc to open Task Manager.<br> Step 2 - Click on the Performance tab.<br> Step 3 - Select Memory (RAM) from the left side.<br> Step 4 - Check how much RAM is being used.<br> Step 5 - If usage is high, go back to Processes tab.<br> Step 6 - Close unnecessary programs to free RAM.<b><br><br>3. Scan for Viruses.</b><br> Step 1 - Open your Antivirus software.<br> Step 2 - Go to Virus & Threat Protection or Scan options.<br> Step 3 - Select Full Scan.Click Scan Now.<br> Step 4 - Wait for the scan to complete.<br> Step 5 - Remove or quarantine any detected threats.<br><br><b>4. Restart the Computer.</b><br> Step 1 - Connect an external storage device (USB drive or external hard disk).<br> Step 2 - Open File Explorer.<br> Step 3 - Locate the files or folders you want to move.<br> Step 4 - Right-click on the file and click Copy.<br> Step 5 - Open the external storage device.<br> Step 6 - Right-click and click Paste.";
}


else{
solution.innerHTML="";
}

solution.scrollIntoView({behavior: "smooth"});

}